In [ ]:
import sys
!{sys.executable} -m pip install pandas

Requirement already satisfied: pandas in /mnt/c/Users/easan.s.2024/Documents/GitHub/FPL-Oracle/.venv/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /mnt/c/Users/easan.s.2024/Documents/GitHub/FPL-Oracle/.venv/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /mnt/c/Users/easan.s.2024/Documents/GitHub/FPL-Oracle/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /mnt/c/Users/easan.s.2024/Documents/GitHub/FPL-Oracle/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
from pathlib import Path
import pandas as pd

# Project root (one level above this notebook's folder)
ROOT = Path.cwd().resolve().parent

player_csv = ROOT / 'data' / 'processed' / '2025-2026_player_stats_by_gameweek_all_clean.csv'
team_csv = ROOT / 'data' / 'processed' / '2025-2026_team_stats_by_gameweek_long_clean.csv'

df_player_2526 = pd.read_csv(player_csv)
df_team_2526 = pd.read_csv(team_csv)

print(f'Player data shape: {df_player_2526.shape}')
print(f'Team data shape: {df_team_2526.shape}')

# Quick preview for exploration
display(df_player_2526.head())
display(df_team_2526.head())

Player data shape: (27459, 99)
Team data shape: (923, 59)

,id,first_name,second_name,web_name,status,news,now_cost,now_cost_rank,now_cost_rank_type,selected_by_percent,...,strength,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id,elo,fotmob_name
0,1,David,Raya Martín,Raya,a,NaN,6.0,89,1.0,36.9,...,5,1305,1355,1340,1390,1270,1320,1,2053,Arsenal
1,10,Myles,Lewis-Skelly,Lewis-Skelly,a,NaN,5.1,238,37.0,2.1,...,5,1305,1355,1340,1390,1270,1320,1,2053,Arsenal
2,100,Junior,Kroupi,Kroupi.Jr,a,NaN,4.6,393,60.0,3.7,...,3,1150,1235,1060,1230,1240,1240,127,1858,AFC Bournemouth
3,101,Caoimhín,Kelleher,Kelleher,a,NaN,4.5,405,23.0,8.1,...,3,1135,1215,1120,1160,1150,1270,130,1838,Brentford
4,102,Ellery,Balcombe,Balcombe,a,NaN,4.0,635,48.0,0.3,...,3,1135,1215,1120,1160,1150,1270,130,1838,Brentford

,match_id,gameweek,kickoff_time,finished,team,team_elo,score,possession,expected_goals_xg,total_shots,...,successful_dribbles_pct,distance_covered,walking_distance,running_distance,sprinting_distance,number_of_sprints,top_speed,side,season,team_name
0,25-26-prem-aston-villa-vs-newcastle-united,1,2025-08-16T11:30:00,True,4.0,1868.57,0.0,60.0,1.43,16.0,...,20.0,110486.0,33858.0,73917.0,2711.0,132.0,35.500000,away,2025-2026,Newcastle
1,25-26-prem-aston-villa-vs-newcastle-united,1,2025-08-16T11:30:00,True,7.0,1872.85,0.0,40.0,0.20,3.0,...,60.0,105914.0,33303.0,70707.0,1904.0,93.0,33.700001,home,2025-2026,Aston Villa
2,25-26-prem-brighton-hove-albion-vs-fulham,1,2025-08-16T14:00:00,True,36.0,1827.14,1.0,50.0,1.48,10.0,...,36.0,112331.0,33872.0,76199.0,2260.0,108.0,32.900002,home,2025-2026,Brighton
3,25-26-prem-brighton-hove-albion-vs-fulham,1,2025-08-16T14:00:00,True,54.0,1781.73,1.0,50.0,0.76,7.0,...,38.0,109216.0,34845.0,72455.0,1916.0,94.0,33.500000,away,2025-2026,Fulham
4,25-26-prem-chelsea-vs-crystal-palace,1,2025-08-17T13:00:00,True,31.0,1835.05,0.0,28.0,0.66,11.0,...,71.0,107554.0,34309.0,71187.0,2058.0,94.0,34.299999,away,2025-2026,Crystal Palace

In [ ]:
import pandas as pd
from pathlib import Path

  # Works whether notebook is run from repo root or preprocessing/
CWD = Path.cwd().resolve()
BASE = CWD / "data" / "processed"
if not BASE.exists():
    BASE = CWD.parent / "data" / "processed"

print("Using base path:", BASE)

teams = pd.read_csv(BASE / "teams.csv")
code_to_name = teams.set_index("code")["name"].to_dict()

team_stats_path = BASE / "2025-2026_team_stats_by_gameweek_long_clean.csv"
df_team = pd.read_csv(team_stats_path)

df_team["team_name"] = pd.to_numeric(df_team["team"], errors="coerce").map(code_to_name)
df_team.to_csv(team_stats_path, index=False)

print("Saved:", team_stats_path)
print("Unmapped rows:", int(df_team["team_name"].isna().sum()))
df_team[["team", "team_name", "gameweek", "season"]].head()

Using base path: /mnt/c/Users/easan.s.2024/Documents/GitHub/FPL-Oracle/data/processed
Saved: /mnt/c/Users/easan.s.2024/Documents/GitHub/FPL-Oracle/data/processed/2025-2026_team_stats_by_gameweek_long_clean.csv
Unmapped rows: 0

   team       team_name  gameweek     season
0   4.0       Newcastle         1  2025-2026
1   7.0     Aston Villa         1  2025-2026
2  36.0        Brighton         1  2025-2026
3  54.0          Fulham         1  2025-2026
4  31.0  Crystal Palace         1  2025-2026

In [ ]:
# === PLAYER DROP CELL (TEAM-MAP SAFE) ===
# Keeps keys needed to map to team stats: name, gameweek, season
player_merge_keys = ['name', 'gameweek', 'season']

drop_cols_player = [
    'id', 'first_name', 'second_name', 'status', 'news', 'fotmob_name', 'pulse_id',
    'now_cost', 'selected_by_percent', 'selected_rank', 'selected_rank_type',
    'cost_change_event', 'cost_change_event_fall', 'cost_change_start', 'cost_change_start_fall',
    'transfers_in_event', 'transfers_out_event', 'transfers_in', 'transfers_out',
    'now_cost_rank', 'now_cost_rank_type', 'form_rank', 'form_rank_type',
    'points_per_game_rank', 'points_per_game_rank_type',
    'influence_rank', 'influence_rank_type', 'creativity_rank', 'creativity_rank_type',
    'threat_rank', 'threat_rank_type', 'ict_index_rank', 'ict_index_rank_type',
    'corners_and_indirect_freekicks_order', 'direct_freekicks_order', 'penalties_order',
    'gw', 'source', 'team_code',
    'form', 'value_form', 'value_season', 'ep_next', 'ep_this', 'points_per_game',
    'chance_of_playing_next_round', 'chance_of_playing_this_round',
    'web_name',
    'strength', 'strength_overall_home', 'strength_overall_away',
    'strength_attack_home', 'strength_attack_away',
    'strength_defence_home', 'strength_defence_away'
]

drop_cols_player = [c for c in drop_cols_player if c not in player_merge_keys]
drop_cols_existing = [c for c in drop_cols_player if c in df_player_2526.columns]
df_player_2526_model = df_player_2526.drop(columns=drop_cols_existing).copy()

print('Dropped columns:', len(drop_cols_existing))
print('Original shape:', df_player_2526.shape)
print('Model shape:', df_player_2526_model.shape)
print('Merge keys present:', {k: (k in df_player_2526_model.columns) for k in player_merge_keys})
df_player_2526_model[['name', 'gameweek', 'season']].head()

Dropped columns: 55
Original shape: (27459, 99)
Model shape: (27459, 44)
Merge keys present: {'name': True, 'gameweek': True, 'season': True}

          name  gameweek     season
0      Arsenal         1  2025-2026
1      Arsenal         1  2025-2026
2  Bournemouth         1  2025-2026
3    Brentford         1  2025-2026
4    Brentford         1  2025-2026

In [ ]:
df_player_2526_model.head()

,event_points,expected_goals_per_90,expected_assists_per_90,expected_goal_involvements_per_90,expected_goals_conceded_per_90,saves_per_90,clean_sheets_per_90,goals_conceded_per_90,starts_per_90,defensive_contribution_per_90,...,tackles,clearances_blocks_interceptions,recoveries,defensive_contribution,season,gameweek,position,player_id,name,elo
0,10,0.00,0.00,0.00,0.64,1.67,0.53,0.60,1.00,0.00,...,0.0,1.0,13.0,0.0,2025-2026,1,Goalkeeper,1,Arsenal,2053
1,0,0.00,0.01,0.01,1.50,0.00,0.00,1.32,0.00,5.29,...,0.0,1.0,0.0,1.0,2025-2026,1,Defender,10,Arsenal,2053
2,1,0.59,0.04,0.63,1.60,0.00,0.44,2.22,1.11,6.43,...,0.0,0.0,0.0,0.0,2025-2026,1,Forward,100,Bournemouth,1858
3,1,0.00,0.00,0.00,1.31,2.60,0.13,1.60,1.00,0.00,...,0.0,4.0,14.0,0.0,2025-2026,1,Goalkeeper,101,Brentford,1838
4,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,2025-2026,1,Goalkeeper,102,Brentford,1838

In [ ]:
# === MERGE PLAYER + TEAM STATS CELL ===
# expects: df_player_2526_model (cleaned player df)
# expects: df_team (team stats df with team_name already mapped from team code)

df_p = df_player_2526_model.copy()
df_t = df_team.copy()

# Normalize join keys
df_p['name'] = df_p['name'].astype(str).str.strip()
df_t['team_name'] = df_t['team_name'].astype(str).str.strip()

df_p['gameweek'] = pd.to_numeric(df_p['gameweek'], errors='coerce')
df_t['gameweek'] = pd.to_numeric(df_t['gameweek'], errors='coerce')

df_p['season'] = df_p['season'].astype(str).str.strip()
df_t['season'] = df_t['season'].astype(str).str.strip()

# Aggregate team rows per team-week-season (handles duplicates, e.g. DGW sources)
team_keys = ['team_name', 'gameweek', 'season']
num_cols = df_t.select_dtypes(include='number').columns.tolist()
num_cols = [c for c in num_cols if c != 'gameweek']
df_t_agg = df_t.groupby(team_keys, as_index=False)[num_cols].mean()

# Merge: player's team name + gameweek + season
df_full_2526 = df_p.merge(
    df_t_agg,
    left_on=['name', 'gameweek', 'season'],
    right_on=['team_name', 'gameweek', 'season'],
    how='left',
    suffixes=('', '_team')
)

print('Player shape:', df_p.shape)
print('Team agg shape:', df_t_agg.shape)
print('Merged shape:', df_full_2526.shape)
print('Rows without team match:', int(df_full_2526['team_name'].isna().sum()))
df_full_2526.head()

Player shape: (27459, 44)
Team agg shape: (753, 55)
Merged shape: (27459, 97)
Rows without team match: 291

,event_points,expected_goals_per_90,expected_assists_per_90,expected_goal_involvements_per_90,expected_goals_conceded_per_90,saves_per_90,clean_sheets_per_90,goals_conceded_per_90,starts_per_90,defensive_contribution_per_90,...,aerial_duels_won,aerial_duels_won_pct,successful_dribbles,successful_dribbles_pct,distance_covered,walking_distance,running_distance,sprinting_distance,number_of_sprints,top_speed
0,10,0.00,0.00,0.00,0.64,1.67,0.53,0.60,1.00,0.00,...,16.0,41.0,9.0,36.0,114560.0,33319.0,77899.0,3342.0,137.0,35.500000
1,0,0.00,0.01,0.01,1.50,0.00,0.00,1.32,0.00,5.29,...,16.0,41.0,9.0,36.0,114560.0,33319.0,77899.0,3342.0,137.0,35.500000
2,1,0.59,0.04,0.63,1.60,0.00,0.44,2.22,1.11,6.43,...,18.0,38.0,8.0,42.0,112254.0,33096.0,75328.0,3830.0,174.0,33.799999
3,1,0.00,0.00,0.00,1.31,2.60,0.13,1.60,1.00,0.00,...,16.0,44.0,7.0,50.0,110983.0,34043.0,75124.0,1816.0,95.0,35.000000
4,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,16.0,44.0,7.0,50.0,110983.0,34043.0,75124.0,1816.0,95.0,35.000000

In [ ]:
# === DROP PER-90 COLUMNS CELL ===
# Remove per-90 features (not needed for single-game prediction rows)

per90_cols = [c for c in df_full_2526.columns if '_per_90' in c]
df_full_2526_no_per90 = df_full_2526.drop(columns=per90_cols).copy()

print('Per-90 columns dropped:', len(per90_cols))
print(per90_cols)
print('Before:', df_full_2526.shape)
print('After :', df_full_2526_no_per90.shape)
df_full_2526_no_per90.head()

Per-90 columns dropped: 9
['expected_goals_per_90', 'expected_assists_per_90', 'expected_goal_involvements_per_90', 'expected_goals_conceded_per_90', 'saves_per_90', 'clean_sheets_per_90', 'goals_conceded_per_90', 'starts_per_90', 'defensive_contribution_per_90']
Before: (27459, 97)
After : (27459, 88)

,event_points,total_points,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,...,aerial_duels_won,aerial_duels_won_pct,successful_dribbles,successful_dribbles_pct,distance_covered,walking_distance,running_distance,sprinting_distance,number_of_sprints,top_speed
0,10,10.0,90.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,16.0,41.0,9.0,36.0,114560.0,33319.0,77899.0,3342.0,137.0,35.500000
1,0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.0,41.0,9.0,36.0,114560.0,33319.0,77899.0,3342.0,137.0,35.500000
2,1,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,18.0,38.0,8.0,42.0,112254.0,33096.0,75328.0,3830.0,174.0,33.799999
3,1,1.0,90.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,16.0,44.0,7.0,50.0,110983.0,34043.0,75124.0,1816.0,95.0,35.000000
4,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.0,44.0,7.0,50.0,110983.0,34043.0,75124.0,1816.0,95.0,35.000000

In [ ]:
# === SAVE FINAL DATAFRAME CSV CELL ===
# Save final preprocessed dataframe to CSV
from pathlib import Path

CWD = Path.cwd().resolve()
BASE = CWD / 'data' / 'processed'
if not BASE.exists():
    BASE = CWD.parent / 'data' / 'processed'

out_path = BASE / '2025-2026_player_team_merged_no_per90.csv'
df_full_2526_no_per90.to_csv(out_path, index=False)

print('Saved:', out_path)
print('Shape:', df_full_2526_no_per90.shape)

Saved: /mnt/c/Users/easan.s.2024/Documents/GitHub/FPL-Oracle/data/processed/2025-2026_player_team_merged_no_per90.csv
Shape: (27459, 88)

In [1]:
# === SELF-CONTAINED: ADD SIDE USING CSVs ===
import pandas as pd
from pathlib import Path

# Resolve data/processed path robustly
CWD = Path.cwd().resolve()
BASE = CWD / 'data' / 'processed'
if not BASE.exists():
    BASE = CWD.parent / 'data' / 'processed'

merged_path = BASE / '2025-2026_player_team_merged_no_per90.csv'
team_stats_path = BASE / '2025-2026_team_stats_by_gameweek_long_clean.csv'

# Load directly from CSVs
df_merged = pd.read_csv(merged_path)
df_team = pd.read_csv(team_stats_path)

# Ensure team_name exists in team stats
if 'team_name' not in df_team.columns:
    teams = pd.read_csv(BASE / 'teams.csv')
    code_to_name = teams.set_index('code')['name'].to_dict()
    df_team['team_name'] = pd.to_numeric(df_team['team'], errors='coerce').map(code_to_name)

# Normalize keys
for d, team_col in [(df_merged, 'name'), (df_team, 'team_name')]:
    d[team_col] = d[team_col].astype(str).str.strip()
    d['gameweek'] = pd.to_numeric(d['gameweek'], errors='coerce')
    d['season'] = d['season'].astype(str).str.strip()

# Build side map only for unambiguous keys
keys = ['team_name', 'gameweek', 'season']
tmp = df_team[keys + ['side']].dropna(subset=['team_name', 'gameweek', 'season']).copy()

side_counts = (
    tmp.groupby(keys, as_index=False)['side']
    .nunique()
    .rename(columns={'side': 'n_unique_side'})
)
single_keys = side_counts[side_counts['n_unique_side'] == 1][keys]

side_map = (
    tmp.merge(single_keys, on=keys, how='inner')
    .drop_duplicates(subset=keys)[keys + ['side']]
)

# Merge side into merged df
df_full_with_side = df_merged.merge(
    side_map,
    left_on=['name', 'gameweek', 'season'],
    right_on=['team_name', 'gameweek', 'season'],
    how='left'
)

# Cleanup duplicate team_name columns if created
if 'team_name_x' in df_full_with_side.columns and 'team_name_y' in df_full_with_side.columns:
    df_full_with_side['team_name'] = df_full_with_side['team_name_x']
    df_full_with_side = df_full_with_side.drop(columns=['team_name_x', 'team_name_y'])

print('Merged shape:', df_merged.shape)
print('With side shape:', df_full_with_side.shape)
print('Ambiguous team-week-season keys:', int((side_counts['n_unique_side'] > 1).sum()))
print('Rows with missing side:', int(df_full_with_side['side'].isna().sum()))

df_full_with_side[['name', 'gameweek', 'season', 'side']].head()

Merged shape: (27459, 88)
With side shape: (27459, 89)
Ambiguous team-week-season keys: 84
Rows with missing side: 3511

          name  gameweek     season  side
0      Arsenal         1  2025-2026  away
1      Arsenal         1  2025-2026  away
2  Bournemouth         1  2025-2026  away
3    Brentford         1  2025-2026  away
4    Brentford         1  2025-2026  away

In [2]:
# === DROP RECOMMENDED TEAM-HEAVY COLUMNS (df_full_with_side) ===
drop_cols_team_excess = [
    # duplicate team identifiers (keep player-side 'name' key)
    'team',
    'team_name',

    # redundant xG/possession decomposition
    'xg_open_play',
    'xg_set_play',
    'own_half',
    'opposition_half',

    # noisy shot decomposition
    'shots_off_target',
    'blocked_shots',
    'hit_woodwork',

    # style descriptors
    'accurate_long_balls',
    'accurate_long_balls_pct',
    'accurate_crosses',
    'accurate_crosses_pct',

    # low-signal event noise
    'fouls_committed',
    'offsides',
    'throws',

    # overlapping duel stats
    'duels_won',
    'ground_duels_won',
    'ground_duels_won_pct',
    'aerial_duels_won',
    'aerial_duels_won_pct',

    # physical tracking block
    'distance_covered',
    'walking_distance',
    'running_distance',
    'sprinting_distance',
    'number_of_sprints',
    'top_speed',
]

# Optional strict pre-match setup:
# drop_cols_team_excess.append('score')

to_drop = [c for c in drop_cols_team_excess if c in df_full_with_side.columns]
df_model = df_full_with_side.drop(columns=to_drop).copy()

print('Dropped:', len(to_drop))
print('Before:', df_full_with_side.shape)
print('After :', df_model.shape)
print('Dropped columns:', to_drop)

Dropped: 27
Before: (27459, 89)
After : (27459, 62)
Dropped columns: ['team', 'team_name', 'xg_open_play', 'xg_set_play', 'own_half', 'opposition_half', 'shots_off_target', 'blocked_shots', 'hit_woodwork', 'accurate_long_balls', 'accurate_long_balls_pct', 'accurate_crosses', 'accurate_crosses_pct', 'fouls_committed', 'offsides', 'throws', 'duels_won', 'ground_duels_won', 'ground_duels_won_pct', 'aerial_duels_won', 'aerial_duels_won_pct', 'distance_covered', 'walking_distance', 'running_distance', 'sprinting_distance', 'number_of_sprints', 'top_speed']